import Image from "next/image";
import Link from "next/link";
import ExpandableSection from "@/app/components/ExpandableSection";
const groups=[
 {id:"foundation",title:"Build your foundation",items:["Website development · Hosting · Management · Analytics","Google My Business setup · Verification · Management · Optimization","Email marketing: publication subscribers · locals · extended network","Social media: content creation · management · ads · support"]},
 {id:"discoverability",title:"Paint the walls",items:["Digital directory optimization: NAP · content & keyword enrichment · data tags · site speed · crawl errors","Local SEO: reputation & review monitoring · geotagging · near-me searches · alt script","Search engine marketing (SEM)"]},
 {id:"advertising",title:"Show it off",items:["Choose: display, social, audio, video, or streaming TV ads","Find your audience by publication readership, consumer composition, geofencing, intent, retargeting, or your owned data","Captivate & convert"]}
];
const Card=({title,children}:{title:string;children:React.ReactNode})=><article className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h3 className="text-2xl font-black text-[#165d70]">{title}</h3><div className="mt-4 space-y-3 leading-7">{children}</div></article>;
export default function Page(){return <main className="mx-auto max-w-screen-lg overflow-hidden bg-[#f5f2ec] text-slate-900 shadow-xl">
 <header className="grid items-center gap-8 bg-[#155d70] px-6 py-14 text-white sm:grid-cols-2 sm:px-12"><div><p className="font-bold uppercase tracking-[.3em]">Digital Evergreen</p><h1 className="mt-4 text-5xl font-black">Your digital journey begins here</h1><p className="mt-6 text-lg leading-8">Your online presence is your story, seen and experienced by every visitor, follower, and click. Trust Evergreen Media’s digital experts to craft a presence that works as hard as you do.</p><p className="mt-6 font-black uppercase leading-7">Get found online · Look good doing it · Bring in better leads · Track what’s working</p></div><Image src="/media-kit/digital-evergreen/visual-04.png" alt="Example of a business presented across digital platforms" width={418} height={555} priority className="mx-auto max-h-96 w-auto"/></header>
 <nav aria-label="Digital services" className="sticky top-0 z-10 flex gap-5 overflow-x-auto bg-white/95 px-5 py-4 text-sm font-bold shadow-sm backdrop-blur">{[...groups.map(x=>[x.id,x.title]),["web","Web & search"],["social","Email & social"],["ads","Digital ads"]].map(([id,label])=><a className="shrink-0 hover:text-[#165d70]" href={`#${id}`} key={id}>{label}</a>)}</nav>
 <section className="grid gap-5 px-5 py-12 sm:grid-cols-3 sm:px-10">{groups.map(g=><Card key={g.id} title={g.title}><ul id={g.id} className="space-y-3">{g.items.map(x=><li key={x}>{x}</li>)}</ul></Card>)}</section>
 <section id="web" className="grid gap-6 bg-white px-5 py-12 sm:grid-cols-2 sm:px-10"><Card title="Website development"><p>Development · Hosting · Management · Training · Analytics</p><p>Custom site development starts at $4,000. 5 page site $2,500 · 3 page site $2,000 · 1 page site $1,200.</p><p>Content Management System training: FREE. Annual hosting: $300; hosting is FREE for the first month.</p></Card><Card title="Search engine establishment"><p>Directory Optimization $150/mo. · Local SEO $500/mo. · Organic SEO $650/mo.</p><p>Search Engine Marketing: custom pricing. Paid Search · Sponsored Copy or Display · Google Network.</p></Card></section>
 <section id="social" className="grid gap-6 px-5 py-12 sm:grid-cols-2 sm:px-10"><Card title="Email marketing"><p>Newsletter Spotlights $200 each or 4/$500 — EGM · Bride · Family · Visitor.</p><p>Advertiser Dedicated $250 each or 4/$600 — EGM · BHB · BHF · FACES.</p><p>Beyond the Brands $450 each — targeted email, up to 250K local deliveries.</p></Card><Card title="Social media management"><p><b>Starter $850/mo.</b> Facebook, Google My Business, +1 channel; 3 posts/week, 12/month; 2 boosts; reporting, planning, strategy call.</p><p><b>Growth $1,200/mo.</b> +2 channels; 4 posts/week, 16/month; 20K impressions; 2 content shoots/year; 2 monthly e-blasts; expanded analytics.</p><p><b>Premium $1,850/mo.</b> +3 channels; 4 posts/week, 16/month; 50K impressions; monthly content shoots; weekly e-blasts; expanded analytics.</p><p>Client-owned asset support and troubleshooting: $150/hour.</p></Card></section>
 <section id="ads" className="bg-[#172d34] px-5 py-12 text-white sm:px-10"><h2 className="text-4xl font-black">Digital ads & paid media</h2><p className="mt-3 text-lg">Display · Video · Audio · Streaming TV — be everywhere your audience already is.</p><div className="mt-7 flex flex-wrap justify-center gap-4">{[["Display Ads","$10–$20 CPM"],["Social Media Ads","$12–$20 CPM"],["Audio Ads","$15–$35 CPM"],["Video/YT Ads","$16–$35 CPM"],["Streaming TV","$20–$45 CPM"]].map(([a,b])=><ExpandableSection key={a} title={a} description="Targeted digital advertising" price={b} tag={`digital-evergreen: ${a}`}/>)}</div><Image src="/media-kit/digital-evergreen/visual-30.png" alt="Sample network of digital advertising platforms" width={2427} height={1706} className="mt-8 max-h-72 w-full object-contain"/></section>
 <footer className="grid gap-5 bg-[#165d70] px-6 py-9 text-white sm:grid-cols-2"><div><b>EVERGREEN MEDIA</b><p>329 Main St. Suite 1 · Rapid City, SD</p><Link href="https://evergreenmediarc.com">evergreenmediarc.com</Link></div><div className="sm:text-right"><b>For more information</b><br/><Link href="mailto:Rick@egmrc.com">Rick | Rick@egmrc.com</Link><br/><Link href="tel:+16053437684;ext=1203">605.343.7684 Ext. 1203</Link></div></footer>
 </main>}
